"""Initial revision

Revision ID: 1d20a5b45c22
Revises: None
Create Date: 2014-10-01 20:43:15.848708

"""

# revision identifiers, used by Alembic.
revision = '1d20a5b45c22'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
