"""Initial revision

Revision ID: 26d50fd99eb7
Revises: 1d20a5b45c22
Create Date: 2014-10-01 20:45:24.349555

"""

# revision identifiers, used by Alembic.
revision = '26d50fd99eb7'
down_revision = '1d20a5b45c22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
