"""empty message

Revision ID: 1621346c645d
Revises: 1d04c7341275
Create Date: 2014-10-12 12:50:50.817853

"""

# revision identifiers, used by Alembic.
revision = '1621346c645d'
down_revision = '1d04c7341275'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
