"""empty message

Revision ID: 1d04c7341275
Revises: 3c7a8f9d5578
Create Date: 2014-10-12 12:47:21.880884

"""

# revision identifiers, used by Alembic.
revision = '1d04c7341275'
down_revision = '3c7a8f9d5578'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column(u'user', sa.Column('role_id', sa.Integer(), nullable=False))
    op.drop_column(u'user', 'role')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('role', postgresql.ENUM(u'admin', u'mod', u'user', u'banned', name='roles'), autoincrement=False, nullable=True))
    op.drop_column(u'user', 'role_id')
    op.drop_table('role')
    ### end Alembic commands ###
