"""empty message

Revision ID: 22d6fbf81b4f
Revises: 2eda8f5679c5
Create Date: 2014-10-12 13:04:24.806731

"""

# revision identifiers, used by Alembic.
revision = '22d6fbf81b4f'
down_revision = '2eda8f5679c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'user_id')
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role_id')
    op.add_column('role', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
