"""empty message

Revision ID: 2de6941922bb
Revises: 1621346c645d
Create Date: 2014-10-12 12:54:49.832710

"""

# revision identifiers, used by Alembic.
revision = '2de6941922bb'
down_revision = '1621346c645d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('user', 'role_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('role', 'user_id')
    ### end Alembic commands ###
