"""empty message

Revision ID: 2eda8f5679c5
Revises: 2de6941922bb
Create Date: 2014-10-12 12:55:47.101260

"""

# revision identifiers, used by Alembic.
revision = '2eda8f5679c5'
down_revision = '2de6941922bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
