"""empty message

Revision ID: 4b36b8de9199
Revises: None
Create Date: 2014-10-12 00:08:21.599655

"""

# revision identifiers, used by Alembic.
revision = '4b36b8de9199'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
