"""empty message

Revision ID: e8c03145ff3
Revises: 22d6fbf81b4f
Create Date: 2014-10-13 20:27:21.674721

"""

# revision identifiers, used by Alembic.
revision = 'e8c03145ff3'
down_revision = '22d6fbf81b4f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
